### ISSUE TITLE
Cross extension calls

### ISSUE THREAD

**Issue by gregorym** [thirdweb-dev/dynamic-contracts#6]
Hey,
Building upgradeable contract is a pain so what you built awesome!

Question about cross extension calls. 
Should I assume that a cross-extension call have the same gas implication as a cross-contract call?

**Comment by nkrishang** [comment]
Hey @gregorym apologies on the hold up! Just got to this.

I wrote a simple benchmark test to compare the cost of cross contract calls vs cross extension calls: https://github.com/thirdweb-dev/dynamic-contracts/blob/nkrishang/issue-6/src/test/CrossExtensionCall.t.sol 

In the above test, you can run `forge test -vvvv` and view the cost comparison. 

High level: when one extension calls another extension, the added cost (compared to cross-contract calls) comes from the lookup performed in `BaseRouter.getExtensionForFunction`

![cost-comparison](https://ipfs.io/ipfs/bafybeidqjagl34lbejm3tvxkvdiuzcrprobps7nz46ql26b6pov6eh63ve/cross-contract-v-extension-call.png)
