### ISSUE TITLE
Parameterize extension setting with extension itself in BaseRouter

### ISSUE THREAD

**Issue by travs** [thirdweb-dev/dynamic-contracts#8]
Right now the abstract `BaseRouter` applies checks on extension modification (add, update, remove) based on execution context only, with this function:

```solidity
function _canSetExtension() internal view virtual returns (bool);
```

I am proposing that we pass in the extension being modified, giving us something like `_canSetExtension(Extension _extension)`.

This allows for extension modification to depend on _what_ is being added.
This enables, for instance, the ability to only allow whitelisted extensions within a given project's ecosystem.

It also enables cross-extension dependencies. For example, the readme mentions that accessing an `IPermission` extension from `MyExtenson` fails if `IPermission` is not added to the router already. With parameterized checks, we could implement dependency logic such that `MyExtension` is not able to be added if `IPermission` is not already added.

Alternatively this behaviour would be possible by making `{add,update,remove}Extension(...)` each `virtual`.

**Comment by joaquim-verges** [comment]
@travs thank you for your proposal! I think this makes a lot of sense and has don't see any drawbacks to it.

Would you like to put up a PR for it? Otherwise we'll take it.

**Comment by travs** [comment]
@joaquim-verges Sure thing! I'll make a PR shortly
